### ISSUE TITLE
Support minimum_time for pipelines that return too quickly

### ISSUE THREAD

**Issue by spencer-cdw** [nick-fields/retry#112]
We have a pipeline that takes 1 hour to run. 
Occasionally see the pipeline silently fails after a few seconds/minutes. 

Unfortunately the failure doesn't raise an exception or an invalid exit code, so the pipline continues on. 

We would like to have a flag similar to the `timeout_minutes`, however rather than setting a celiing for the maximum time the task should run, we want a minimum time that the task should have taken

```
      - name: ${{ matrix.image }}
        uses: nick-fields/retry@v2
        with:
          min_time: 60 #<----------------------------- desired feature
          timeout_minutes: 180 # 3 hours
          polling_interval_seconds: 10
          max_attempts: 2
          retry_on: error
          command: "${{ env.PKR_VAR_root_file_path }}/actions/build-images.sh"
          ```
