### ISSUE TITLE
after timeout, the whole run fails without another attempt

### ISSUE THREAD

**Issue by gingerlime** [nick-fields/retry#114]
**Describe the bug**
after timeout, the whole run fails without another attempt

**Expected behavior**
as far as I can tell from the documentation, the timeout applies to each retry, so if it times-out on the first time, it will retry again etc

**Screenshots**
```
      - name: run bats tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: |
            docker image ls -a
            for filename in tests/*.bats; do sudo bats --tap "$filename" || exit 1; done
```

```
/home/runner/work/_actions/nick-fields/retry/v2/dist/index.js:3199
            throw err;
            ^

Error: kill EPERM
    at process.kill (node:internal/process/per_thread:220:13)
    at killPid (/home/runner/work/_actions/nick-fields/retry/v2/dist/index.js:3209:17)
    at /home/runner/work/_actions/nick-fields/retry/v2/dist/index.js:3186:21
    at Array.forEach (<anonymous>)
    at /home/runner/work/_actions/nick-fields/retry/v2/dist/index.js:3184:23
    at Array.forEach (<anonymous>)
    at killAll (/home/runner/work/_actions/nick-fields/retry/v2/dist/index.js:3183:27)
    at /home/runner/work/_actions/nick-fields/retry/v2/dist/index.js:3174:13
    at ChildProcess.onClose (/home/runner/work/_actions/nick-fields/retry/v2/dist/index.js:3230:17)
    at ChildProcess.emit (node:events:527:28) {
  errno: -1,
  code: 'EPERM',
  syscall: 'kill'
}
```

**Logs**
[run](https://github.com/MinimalCompact/thumbor/actions/runs/5265300055/jobs/9517755971)

[raw log with debug](https://pipelines.actions.githubusercontent.com/serviceHosts/9b122c6a-c90a-41a5-ad89-04334bcf60f1/_apis/pipelines/1/runs/91/signedlogcontent/2?urlExpires=2023-06-14T09%3A24%3A51.4212575Z&urlSigningMethod=HMACV1&urlSignature=POxIokUDy2dVmlcr59WTYTE0xjoG8bh2f4hOEhJfGVg%3D)
