### ISSUE TITLE
Get EPERM error on timeout

### ISSUE THREAD

**Issue by cunj123** [nick-fields/retry#124]
**Describe the bug**
When timeout is reached, the action tries to kill the child process, but it throws an EPERM error
```
/home/runner/work/poco/poco/.github/actions/retry-action/dist/index.js:3353
            throw err;
            ^

Error: kill EPERM
    at process.kill (node:internal/process/per_thread:221:13)
    at killPid (/home/runner/work/poco/poco/.github/actions/retry-action/dist/index.js:3363:17)
    at /home/runner/work/poco/poco/.github/actions/retry-action/dist/index.js:3340:21
    at Array.forEach (<anonymous>)
    at /home/runner/work/poco/poco/.github/actions/retry-action/dist/index.js:3338:23
    at Array.forEach (<anonymous>)
    at killAll (/home/runner/work/poco/poco/.github/actions/retry-action/dist/index.js:3337:27)
    at /home/runner/work/poco/poco/.github/actions/retry-action/dist/index.js:3328:13
    at ChildProcess.onClose (/home/runner/work/poco/poco/.github/actions/retry-action/dist/index.js:3384:17)
    at ChildProcess.emit (node:events:513:28) {
  errno: -1,
  code: 'EPERM',
  syscall: 'kill'
}
```

Configuration:
```
      - uses: nick-fields/retry@v2.9.0
        with:
          timeout_minutes: 1
          max_attempts: 3
          retry_on: any
          command: >-
            sudo -s
            ./ci/runtests.sh TSAN
```

**Expected behavior**
Should not throw, and the command should be retried
