### ISSUE TITLE
Use outputs of `command` as step outputs

### ISSUE THREAD

**Issue by ffisc** [nick-fields/retry#131]
**Describe the bug**

It would be great it this worked

```yaml
- id: step_1
    uses: nick-fields/retry@v3
    with:
      command: echo "foo=bar" >> $GITHUB_OUTPUT
- run: echo ${{ steps.step_1.outputs.foo }}
```

**Expected behavior**
See above

**Screenshots**
N/A

**Logs**
N/A
