### ISSUE TITLE
Feature Request: retry another github action

### ISSUE THREAD

**Issue by jduan-highnote** [nick-fields/retry#137]
Is it possible to retry another github action? For example, if my workflow uses the following to install a JDK:

```
      - name: Retry Set up JDK if failed
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
```

Is it possible to use this action to retry it?

My current workaround is this:
```
      - name: Set up JDK
        id: setup_jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Sleep a bit
        run: sleep 5
      - name: Retry Set up JDK if failed
        if: steps.setup_jdk.outcome == 'failure'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
```

which is not elegant.
