### ISSUE TITLE
Retry on timeout stops working when `retry_on_exit_code` is specified

### ISSUE THREAD

**Issue by kdomenicucci-kg** [nick-fields/retry#145]
**Describe the bug**

When both a `timeout` and `retry_on_exit_code` are specified, timeouts are not retried.

```
   - name: "Example"
      uses: nick-fields/retry@v3
      with:
        max_attempts: 2
        retry_on: any
        timeout_minutes: 10
        retry_on_exit_code: 2
        command: <COMMAND>
```

**Expected behavior**

If `retry_on` is set to `any` (timeout + error), and `timeout_minutes` and `retry_on_exit_code` have valid values specified, then both timeouts and specific exit codes should support retrying.

**Screenshots**

In the code, it looks like this happens because `retry_on_exit_code` is evaluated without considering whether the command has finished running. It could be that fixing this issue is as simple as checking that the command has finished executing before evaluating exit codes.
![Screenshot 2024-11-21 at 10 26 44 AM](https://github.com/user-attachments/assets/9441d3df-159e-4e9f-8602-eef2fd54ccbe)
