### ISSUE TITLE
Getting started with uses step

### ISSUE THREAD

**Issue by idomic** [nick-fields/retry#68]
**Describe the bug**
I have this Setup R step which fails frequently in the CI
steps:
    - uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2.2.2

It's unclear to me how do I use this package and retry this step up to 3 times on failure.

**Expected behavior**
Expected to see some docs on it.

**Comment by nick-fields** [comment]
This action is only intended to replace the `run` step as mentioned [here](https://github.com/nick-fields/retry/blob/master/README.md?plain=1#L3).  

If you want to retry a `uses` step, I suggest combining `continue-on-error` and conditionals based on outcome of step.  It's not pretty but it'll do

Untested example:

```yaml
- name: A flaky action
  id: first-attempt
  continue-on-error: true
  uses: r-lib/actions/setup-r@v2.2.2
- name: Second attempt at flaky action
  if: ${{ steps.happy_path_continue_on_error.outcome }} != 'success'
  uses: r-lib/actions/setup-r@v2.2.2
```
