### ISSUE TITLE
Allow to specify a working-directory

### ISSUE THREAD

**Issue by Luc45** [nick-fields/retry#89]
**Describe the bug**
My workflow expects the script to be executed from a specific directory, so I use something like this:

```yml
- name: Do foo
  working-directory: some-dir
  run: ./foo
```

When porting this to retry, I cannot set the `working-directory` for the step, as it only works with `run`.

Similar issue: https://stackoverflow.com/questions/67299058/running-github-actions-for-uses-in-another-directory

**Expected behavior**
Retry should allow to specify a `working-directory`

**Screenshots**

![image](https://user-images.githubusercontent.com/9341686/182908391-5b90a7a4-074d-43bd-9647-8dd04ae33c3c.png)

**Logs**
Enable [debug logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging) then attach the [raw logs](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) (specifically the raw output of this action).

**Comment by tamascsaba** [comment]
It would be really great to support the default working-directory too.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-set-the-default-shell-and-working-directory

**Comment by martijnvdbrug** [comment]
Great action! I defined my default working directory in the action, and all other steps use this directory except the retry-action.
```yml
jobs:
  test:
    name: E2e testing
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/e2e
```

Supporting this would be great!

**Comment by tamirble** [comment]
I'm joining this request 🙏

**Comment by ShubhamRasal** [comment]
I'm joining this request too

**Comment by NickDub** [comment]
I'm joining this request too

**Comment by bdlake** [comment]
Love this action, but would love it more if `working-directory` was an input :)

**Comment by zburgermeiszter** [comment]
Less than ideal, but it is possible to make it work in a folder by using a multi-line command and use `cd`.

```
- name: Install npm dependencies
        uses: nick-fields/retry@v3
        if: ${{ steps.setupNode.outputs.cache-hit != 'true' }}
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            cd apps/frontend
            npm ci
```

**Comment by dbudwin** [comment]
@zburgermeiszter A simpler way to do this would be:

```
- name: Install npm dependencies
  uses: nick-fields/retry@v3
  if: ${{ steps.setupNode.outputs.cache-hit != 'true' }}
  with:
    timeout_minutes: 10
    max_attempts: 3
    command: npm ci --prefix apps/frontend
```
